exclude:
    - "packages/frontend/src/assets/**/*.ts"
    - "packages/utils/src/**/*.ts"
    - "packages/frontend/src/uberCore/**/*.ts"
    - "packages/frontend/src/inputs/**/*.ts"
    - "packages/frontend/src/universe/architecture/**/*.ts"
    - "packages/game/src/settings.ts"
    - "packages/game/src/i18n.ts"
