//  This file is part of Cosmos Journeyer
//
//  Copyright (C) 2024 Barthélemy Paléologue <barth.paleologue@cosmosjourneyer.com>
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Affero General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Affero General Public License for more details.
//
//  You should have received a copy of the GNU Affero General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

/**
 * @see https://en.wikipedia.org/wiki/List_of_proper_names_of_stars
 * @see https://www.aavso.org/constellation-names-and-abbreviations
 */
const constellationNames: string[] = [
    "Andromedae",
    "Antliae",
    "Apodis",
    "Aquarii",
    "Aquilae",
    "Arae",
    "Archimediae",
    "Arietis",
    "Arii",
    "Aurigae",
    "Azophi",
    "Barnard",
    "Berenices",
    "Boötis",
    "Botes",
    "Caeli",
    "Cameliae",
    "Camelopardalis",
    "Cancri",
    "Canesis",
    "Cannonis",
    "Canis",
    "Carteri",
    "Capricorni",
    "Carinae",
    "Cassini",
    "Cassiopeiae",
    "Centauri",
    "Cephei",
    "Ceti",
    "Chamaeleontis",
    "Circini",
    "Columbae",
    "Comae",
    "Conway",
    "Copernici",
    "Coronae",
    "Corvi",
    "Crateris",
    "Crucis",
    "Curi",
    "Cygni",
    "Darwini",
    "Delphini",
    "Da Vinci",
    "Delphini",
    "Descartes",
    "Dijkstrae",
    "Doradus",
    "Draconis",
    "Drakes",
    "Eich",
    "Einsteini",
    "Equulei",
    "Eratosthenis",
    "Eridani",
    "Euclidae",
    "Euleris",
    "Europae",
    "Fornacis",
    "Gaussi",
    "Galilei",
    "Geminorum",
    "Gruis",
    "Hamiltoni",
    "Hawking",
    "Herculis",
    "Herschel",
    "Hopperae",
    "Horologii",
    "Hubblis",
    "Huygentis",
    "Hyades",
    "Hydrae",
    "Hydri",
    "Hypatiae",
    "Indi",
    "Kapteyni",
    "Kepleris",
    "Lacertae",
    "Leavitis",
    "Leonis",
    "Leporis",
    "Librae",
    "Lovelace",
    "Lupi",
    "Lyncis",
    "Lyrae",
    "Mensae",
    "Messier",
    "Microscopii",
    "Mobii",
    "Monocerotis",
    "Muscae",
    "Neumanni",
    "Newtonis",
    "Normae",
    "Octantis",
    "Ophiuchi",
    "Orionis",
    "Pavonis",
    "Pegasi",
    "Persei",
    "Phoenicis",
    "Pictoris",
    "Piscium",
    "Piscis",
    "Ptolemæi",
    "Puppis",
    "Pythagorae",
    "Pyxidis",
    "Reticuli",
    "Saganis",
    "Sagittae",
    "Sagittarii",
    "Scorpii",
    "Sculptoris",
    "Scuti",
    "Serpentis",
    "Sextantis",
    "Tauri",
    "Telescopii",
    "Torvaldi",
    "Trianguli",
    "Tucanae",
    "Turingi",
    "Ursae",
    "Velorum",
    "Virginis",
    "Volantis",
    "Vulpeculae",
    "Weierstrass",
    "Zeno",
    "Zimmerman",
];

const greekLetters: string[] = [
    "Alpha",
    "Beta",
    "Gamma",
    "Delta",
    "Epsilon",
    "Zeta",
    "Eta",
    "Theta",
    "Iota",
    "Kappa",
    "Lambda",
    "Mu",
    "Nu",
    "Xi",
    "Omicron",
    "Pi",
    "Rho",
    "Sigma",
    "Tau",
    "Upsilon",
    "Phi",
    "Chi",
    "Psi",
    "Omega",
];

/**
 * Generates a star name given a noise based random number generator and the given sample step
 * @param rng A noise based random number generator with a range of [0, 1]
 * @param baseStep The sample step
 */
export function generateStarName(rng: (step: number) => number, baseStep: number): string {
    const constellation = constellationNames[Math.floor(rng(baseStep) * constellationNames.length)];
    const greekLetter = greekLetters[Math.floor(rng(baseStep + 1) * greekLetters.length)];
    return `${greekLetter} ${constellation}`;
}
