export const Settings = {
    UNIVERSE_SEED: Math.PI,
    EARTH_RADIUS: 10e3, // target is 6000e3
    AU: 150e9, // target is 150e9

    VERTEX_RESOLUTION: 64,
    MIN_DISTANCE_BETWEEN_VERTICES: 4,

    CLOUD_LAYER_HEIGHT: 15e3,
    ATMOSPHERE_HEIGHT: 100e3,
    OCEAN_DEPTH: 7e3,

    TIME_MULTIPLIER: 1,
    CHUNK_RENDER_DISTANCE_MULTIPLIER: 3,
    ENABLE_VOLUMETRIC_CLOUDS: false,
    SEED_HALF_RANGE: 1e6,
    C: 299792458,
    FOV: (92 * Math.PI) / 180
};
