//  This file is part of Cosmos Journeyer
//
//  Copyright (C) 2024 Barthélemy Paléologue <barth.paleologue@cosmosjourneyer.com>
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU Affero General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU Affero General Public License for more details.
//
//  You should have received a copy of the GNU Affero General Public License
//  along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { getNeighborStarSystemCoordinates } from "../../utils/getNeighborStarSystems";
import { parseDistance } from "../../utils/strings/parseToStrings";
import { Settings } from "../../settings";
import { uniformRandBool } from "extended-random";
import { generateSightseeingMissions } from "../../missions/generateSightSeeingMissions";
import { Player } from "../../player/player";
import { MissionContainer } from "./missionContainer";
import { getRngFromSeed } from "../../utils/getRngFromSeed";
import { OrbitalFacilityModel } from "../../architecture/orbitalObjectModel";
import { StarSystemDatabase } from "../../starSystem/starSystemDatabase";
import { DeepReadonly } from "../../utils/types";

/**
 * Generates all missions available at the given space station for the player. Missions are generated based on the current timestamp (hourly basis).
 * @param stationModel The space station model where the missions are generated
 * @param player The player for which the missions are generated
 * @returns The DOM element containing the generated missions as HTML
 */
export function generateMissionsDom(
    stationModel: DeepReadonly<OrbitalFacilityModel>,
    player: Player,
    starSystemDatabase: StarSystemDatabase
): HTMLDivElement {
    const starSystemModel = starSystemDatabase.getSystemModelFromCoordinates(stationModel.starSystemCoordinates);
    if (starSystemModel === null) {
        throw new Error("Cannot generate missions for a space station in an unknown star system");
    }

    const sightSeeingMissions = generateSightseeingMissions(
        stationModel,
        starSystemModel,
        starSystemDatabase,
        player,
        Date.now()
    );

    const starSystem = starSystemModel;
    const neighborSystems = getNeighborStarSystemCoordinates(starSystem.coordinates, 75, starSystemDatabase);

    const rng = getRngFromSeed(stationModel.seed);

    let neighborSpaceStations: [DeepReadonly<OrbitalFacilityModel>, number][] = [];
    neighborSystems.forEach(([coordinates, position, distance], index) => {
        const systemModel = starSystemDatabase.getSystemModelFromCoordinates(coordinates);
        if (systemModel === null) {
            throw new Error("System model not found for coordinates generated by getNeighborStarSystemCoordinates");
        }
        const spaceStations = systemModel.orbitalFacilities.map<[DeepReadonly<OrbitalFacilityModel>, number]>(
            (stationModel) => {
                return [stationModel, distance];
            }
        );
        neighborSpaceStations = neighborSpaceStations.concat(spaceStations);
    });

    const contactStations = neighborSpaceStations
        // prune list randomly based on distance
        .filter(([station, distance], index) =>
            uniformRandBool(1.0 / (1.0 + 0.02 * (distance * distance)), rng, 325 + index)
        )
        // filter out stations of the same faction
        .filter(([station, distance]) => station.faction === stationModel.faction);

    contactStations.sort((a, b) => a[1] - b[1]);

    const htmlRoot = document.createElement("div");

    const missionH2 = document.createElement("h2");
    missionH2.innerText = "Missions";
    htmlRoot.appendChild(missionH2);

    const explorationMissionH3 = document.createElement("h3");
    explorationMissionH3.innerText = "Exploration";
    htmlRoot.appendChild(explorationMissionH3);

    const missionList = document.createElement("div");
    missionList.className = "missionList";
    htmlRoot.appendChild(missionList);

    sightSeeingMissions.forEach((mission) => {
        const missionContainer = new MissionContainer(mission, player, starSystemDatabase);
        missionList.appendChild(missionContainer.rootNode);
    });

    const terraformationMissionH3 = document.createElement("h3");
    terraformationMissionH3.innerText = "Terraformation";
    htmlRoot.appendChild(terraformationMissionH3);

    const tradingMissionH3 = document.createElement("h3");
    tradingMissionH3.innerText = "Trading";
    htmlRoot.appendChild(tradingMissionH3);

    contactStations.forEach(([station, distance]) => {
        const stationP = document.createElement("p");
        stationP.innerText = `${station.name} in ${starSystem.name} (${parseDistance(distance * Settings.LIGHT_YEAR)})`;
        htmlRoot.appendChild(stationP);
    });

    return htmlRoot;
}
