name: Deploy Game (GitHub Pages)
on:
    workflow_dispatch:

permissions:
    contents: write

concurrency:
    group: deploy_game_gh_pages
    cancel-in-progress: true

jobs:
    deploy_game_gh_pages:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js with pnpm
              uses: pnpm/action-setup@v4

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Check formatting
              run: pnpm run format:check

            - name: Lint project
              run: pnpm run lint

            - name: Test project
              run: pnpm test:unit

            - name: Build project
              run: pnpm build

            - name: Build doc
              run: pnpm doc

            - name: Move doc to dist
              run: mv packages/game/doc packages/game/dist/doc

            - name: Deploy to GitHub Pages (Production)
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: packages/game/dist
                  branch: gh-pages
                  clean-exclude: pr-preview
                  force: false
