name: Deploy PR previews
concurrency: preview-${{ github.ref }}
on:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
            - closed

permissions:
    contents: write
    pull-requests: write

jobs:
    deploy-preview:
        timeout-minutes: 10
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js with pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - run: pnpm i && pnpm run build
              if: github.event.action != 'closed'

            - name: Deploy to GitHub Pages (PR-Preview)
              uses: rossjrw/pr-preview-action@v1
              with:
                  source-dir: ./dist
                  preview-branch: gh-pages
                  umbrella-dir: pr-preview
                  action: auto
